name: Engine Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  engine-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run Engine tests
        run: |
          bash .github/workflows/test.sh engine/
