name: Engine Tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  engine-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Run Engine tests
        run: |
          cd engine
          pwd
          cargo test --verbose
