name: Server Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  server-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run Server tests
        run: |
          bash .github/workflows/test.sh server/
