name: Server Tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  server-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run Server tests
        run: |
          cd server
          pwd
          cargo test --verbose
